package com.cancer.yaqeen.presentation.util

object Constants {
    const val UNIVERSITY_NAME_KEY = "UNIVERSITY_NAME_KEY"
    const val REQUEST_UNIVERSITY_KEY = "REQUEST_UNIVERSITY_KEY"

    const val DATE_SELECTED_KEY = "DATE_SELECTED_KEY"
    const val REQUEST_DATE_KEY = "REQUEST_DATE_KEY"

    const val REMINDER_TIME_KEY = "REMINDER_TIME_KEY"
    const val REQUEST_REMINDER_TIME_KEY = "REQUEST_REMINDER_TIME_KEY"

    const val MEDICATION_ID_KEY = "MEDICATION_ID_KEY"
    const val REQUEST_MEDICATION_ID_KEY = "REQUEST_MEDICATION_ID_KEY"

    const val USER_LOG_IN_KEY = "USER_LOG_IN_KEY"
    const val REQUEST_USER_LOG_IN_KEY = "REQUEST_USER_LOG_IN_KEY"

    const val CAMERA_KEY = "CAMERA_KEY"
    const val FILE_KEY = "FILE_KEY"
    const val REQUEST_METHOD_ATTACHED_FILE_KEY = "REQUEST_USER_LOG_IN_KEY"

    const val IMAGE_URI_KEY = "IMAGE_URI_KEY"
    const val REQUEST_TAKE_PICTURE_KEY = "REQUEST_TAKE_PICTURE_KEY"

    const val PHOTO_ID_KEY = "PHOTO_ID"
    const val TITLE_KEY = "TITLE"
    const val BODY_KEY = "BODY"
    const val ACTION_KEY = "ACTION"
    const val DETAILS_KEY = "DETAILS"
    const val NOTIFICATION_ID = "NOTIFICATION_ID"
    const val BUNDLE_DATA = "BUNDLE_DATA"
    const val OBJECT_JSON = "OBJECT_JSON"
    const val MEDICATION = "MEDICATION"
    const val ROUTINE_TEST = "ROUTINE_TEST"
    const val MEDICAL_APPOINTMENT = "MEDICAL_APPOINTMENT"
    const val IGNORE_NOTIFICATION_ACTION = "IGNORE_NOTIFICATION_ACTION"
    const val OPEN_MEDICATION_WINDOW_ACTION = "OPEN_MEDICATION_WINDOW_ACTION"
    const val OPEN_ROUTINE_TEST_WINDOW_ACTION = "OPEN_ROUTINE_TEST_WINDOW_ACTION"
    const val OPEN_MEDICAL_APPOINTMENT_WINDOW_ACTION = "OPEN_MEDICAL_APPOINTMENT_WINDOW_ACTION"
    const val UPDATE_LOCAL_SCHEDULES_ACTION = "UPDATE_LOCAL_SCHEDULES_ACTION"
    const val UPDATE_LOCAL_MEDICATION_ACTION = "UPDATE_LOCAL_MEDICATION_ACTION"
    const val UPDATE_LOCAL_ROUTINE_TEST_ACTION = "UPDATE_LOCAL_ROUTINE_TEST_ACTION"
    const val ACTION_IGNORE_BUTTON_ID = 50

    const val IMAGE_URI = "IMAGE_URI"
    const val IMAGE_URL = "IMAGE_URL"

    const val SYMPTOM_KEY = "SYMPTOM_KEY"
    const val REQUEST_SYMPTOM_KEY = "REQUEST_SYMPTOM_KEY"

    const val MAX_QUOTES = 2

    const val MAX_POSITION_TO_SCROLL = 2

    const val INIT_SELECTED_POSITION = -1

    const val REPEAT_INTERVAL_TIME_IN_HOUR = 3
}

