package com.cancer.yaqeen.presentation.util.google_analytics

object GoogleAnalyticsAttributes {

    const val APP_VERSION = "Application_Version"
    const val DEVICE_MODEL = "Device_Model"
    const val ACTION_DATE_TIME = "Action_Date_Time"
    const val SELECTED_LANGUAGE = "Selected_Language"
    const val LOGGED_IN = "Logged_In"
    const val USER_ID = "User_ID"
    const val USER_NAME = "User_Name"
    const val ERROR = "Error"
    const val INTEREST_NAME = "Interest_Name"
    const val SCHEDULING_PERMISSIONS_ARE_GRANTED = "Scheduling_Permissions_Are_Granted"
    const val ARTICLE_ID = "Article_ID"
    const val ARTICLE_LINK = "Article_Link"
    const val USER_PROFILE = "User_Profile"
    const val CAPSULE_NAME = "Capsule_Name"
    const val MEDICATION_TYPE = "Medication_Type"
    const val STRENGTH_AMOUNT = "Strength_Amount"
    const val UNIT_TYPE = "Unit_Type"
    const val REMINDER_TIME = "Reminder_Time"
    const val REMINDER_TIME_BEFORE = "Reminder_Time_Before"
    const val START_DATE = "Start_Date"
    const val TIME = "Time"
    const val PERIOD_TIME = "Period_Time"
    const val DAYS = "Days"
    const val DOSAGE_AMOUNT = "Dosage_Amount"
    const val NOTES = "Notes"
    const val MEDICATION = "Medication"
    const val DOCTOR_NAME = "Doctor_Name"
    const val DOCTOR_LOCATION = "Doctor_Location"
    const val DOCTOR_PHONE_NUMBER = "Doctor_Phone_Number"
    const val MEDICAL_REMINDER = "Medical_Reminder"
    const val ROUTINE_TEST_NAME = "Routine_Test_Name"
    const val PHOTO_ATTACHED = "Photo_Attached"
    const val ROUTINE_TEST = "Routine_Test"
    const val SYMPTOMS_TYPES = "Symptom_Types"
    const val SYMPTOM = "Symptom"
    const val DETAILS = "Details"
}